# Slingshot SystemVerilog language server configuration file
# https://github.com/mattyoung101/slingshot

# Config file version
version = "1.0.0"

# List of include directories, relative to project root, to search for SystemVerilog files.
# Note: The project root directory is usually the Git root directory.
# This option is used to configure Verilator linting, to resolve `include directives, and to index
# multi-file projects, so it's very important that this is correct and kept up to date.
include_dirs = [
  "test_data"
  # ... any other RTL source directories here ...
]
