name: "Release"

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Specify tag to create"
        required: true

jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CMAKE_CXX_COMPILER_LAUNCHER: ccache
      CMAKE_C_COMPILER_LAUNCHER: ccache
      CC: /usr/lib/ccache/clang-21
      CXX: /usr/lib/ccache/clang++-21
    permissions: write-all
    steps:
      - uses: actions/checkout@v5

      - name: Install Clang
        run: cd /tmp;
          wget https://apt.llvm.org/llvm.sh;
          chmod +x llvm.sh;
          sudo ./llvm.sh 21
        if: ${{matrix.os}} != 'windows-2022'

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          create-symlink: true

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '4.1.x'

      - name: Setup mold
        uses: rui314/setup-mold@v1
        with:
          make-default: true

      - name: Install more system deps
        run: sudo apt update; sudo apt install --yes clang ninja-build libboost-all-dev

      - name: Build
        run: cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXPORT_COMPILE_COMMANDS=1
          -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_C_COMPILER_LAUNCHER=ccache;
          cd build;
          ninja

      - name: Package
        run: cd build; cpack -G DEB; cpack -G RPM; cpack -G TXZ; cpack -G ZIP;

      - name: Create Release
        id: create-release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag }}
          name: ${{ github.event.inputs.tag }}
          draft: true
          prerelease: false

      - name: Upload assets
        run: |
          cd build;
          for artefact in slingshot-*; do
            gh release upload ${{ github.event.inputs.tag }} $artefact;
          done;
